name: Unit Tests CI

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.x

      - name: Install Dependencies
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -r requirements.txt -r requirements-dev.txt
          python3 -m pip install -e ./

      - name: Run Tests
        run: pytest ./tests/
